- name: "Create proxy_net"
  tags: traefik_deploy
  become: True
  docker_network:
    name: proxy_net

- name: "Create dest folder"
  tags: 
    - traefik_deploy
  file:
    state: directory
    name: "/tmp/traefikproxy"

- name: "Create traefik acme and toml files location"
  become: True
  tags:
    - traefik_deploy
  file:
    state: directory
    name: "{{traefik_files_location}}"

- name: "Create acme.json"
  become: True
  tags: traefik_deploy
  file:
    state: touch
    mode: 0600
    name: "{{traefik_files_location}}/acme.json"

- name: "Upload configuration file"
  become: True
  tags: traefik_deploy
  template:
    src: traefik.j2
    dest: "{{traefik_files_location}}/traefik.toml"

- name: "Creating a tor hidden service private key if there is none..."
  include: gen_rsa.yml
  tags: traefik_deploy
  when: tor_hidden_service_private_key == None and
        TOR_HH == True

- name: "Write docker-compose"
  tags: 
    - traefik_deploy
  template:
    src: docker-compose.j2
    dest: /tmp/traefikproxy/docker-compose.yml

- name: "Deploy traefik proxy"
  become: True
  tags: 
    - traefik_deploy
  docker_service:
    state: present
    project_src: /tmp/traefikproxy

- name: "Waiting for tor container to come up..."
  tags: traefik_deploy
  when: TOR_HH == True
  pause:
    seconds: 10

- name: "Getting onion url..."
  tags: traefik_deploy
  become: True
  command: docker exec -i traefikproxy_torhh_1 onions
  register: onions
  when: TOR_HH == True

- debug:
    msg: "Onion url: {{ onions.stdout }}"
  when: TOR_HH == True
  tags: traefik_deploy

- name: "Remove docker-compose folder"
  become: True
  tags:
    - traefik_deploy
  file:
    name: /tmp/traefikproxy
    state: absent

